stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
    outs:
      - artifacts/preprocessor.pkl
      - artifacts/model.pkl